Title: apache_status: HTTPS support for Python 2.6, 3.0, 3.1, 3.2, 3.3, 3.4
Class: feature
Compatible: compat
Component: checks
Date: 1614172315
Edition: cre
Knowledge: undoc
Level: 1
Version: 2.1.0b1

In some python versions (2.6, 3.0, 3.1, 3.2, 3.3, 3.4) the agent plugin 'apache_status'
crashed with the error message: "Exception (...: urlopen() got an unexpected keyword argument 'context'".
This happens only if an HTTPS connection is established.
The reason for this is that in previous Python versions "urllib.urlopen" did not support the 'context' parameter.
This werk introduces an alternative handling of "urllib.urlopen" for affected python versions.
If you want to use this feature you have to redeploy this agent plugin.
