[//]: # (werk v2)
# Diagnostics: Fix File size collection failing over temporary files

key        | value
---------- | ---
date       | 2025-06-03T11:16:27+00:00
version    | 2.4.0p3
class      | fix
edition    | cre
component  | wato
level      | 1
compatible | yes

The diagnostic dump collection could fail with the following error before:

```
        List of all files in the site including
        their size
        ERROR - Traceback (most recent call last):
  File "/omd/sites/gui_e2e_central/lib/python3/cmk/base/diagnostics.py", line 272, in _get_filepaths
    for filepath in element.add_or_get_files(tmp_dump_folder):
  File "/omd/sites/gui_e2e_central/lib/python3/cmk/base/diagnostics.py", line 406, in add_or_get_files
    infos = self._collect_infos()
            ^^^^^^^^^^^^^^^^^^^^^
  File "/omd/sites/gui_e2e_central/lib/python3/cmk/base/diagnostics.py", line 446, in _collect_infos
    str(f.stat().st_size),
        ^^^^^^^^
  File "/omd/sites/gui_e2e_central/lib/python3.12/pathlib.py", line 840, in stat
    return os.stat(self, follow_symlinks=follow_symlinks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/omd/sites/gui_e2e_central/var/check_mk/web/cmkadmin/.session_info.mk.newodhsmg3r'
```

These temporary files are created by Checkmk while writing files and are now
skipped by the collection.
